
development:
  secret_key_base: adbfccfa754fe314dd2781aa00faca8522ef56e908e026218a918c4530a5f264778acfd0b370943eff1b80f49d30478786bde581ab235f9d6e61905da934fea7
  marvel_api_private_key: <%= ENV['MARVEL_PRIVATE_KEY'] %>
  marvel_api_public_key: <%= ENV['MARVEL_PUBLIC_KEY'] %>

test:
  secret_key_base: 2e93c146bedfb3100599e72af48bf0fc16dda4a6c2062edd4da5999df6c30b7cda1a713536a67089474a0f60cd0992498fbdbe7c776f4871ca88c03015836c4f
  marvel_api_private_key: 'private key'
  marvel_api_public_key: 'public key'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  marvel_api_private_key: <%= ENV['MARVEL_PRIVATE_KEY'] %>
  marvel_api_public_key: <%= ENV['MARVEL_PUBLIC_KEY'] %>
